#!/usr/bin/env bash
# One-command install of the AI Calling Agent with Docker.
#
#   ./install.sh                 run on this computer (http://localhost:3000)
#   ./install.sh calls.acme.com  run on a server with HTTPS for that domain
#                                (point the domain's DNS at the server first)
#
# Creates .env with fresh secrets on the first run, starts everything, and
# prints the link that creates the admin account. Safe to re-run: it keeps
# the existing .env and just rebuilds and restarts.
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; then
  echo "Docker with the compose plugin is required: https://docs.docker.com/get-docker/" >&2
  exit 1
fi

random_hex() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }

if [ ! -f .env ]; then
  domain="${1:-}"
  {
    echo "# Generated by install.sh on $(date -u +%Y-%m-%d). Keep this file private."
    echo "SESSION_SECRET=$(random_hex 32)"
    echo "POSTGRES_PASSWORD=$(random_hex 16)"
    if [ -n "$domain" ]; then
      echo "DOMAIN=$domain"
      echo "PUBLIC_URL=https://$domain"
      echo "DASHBOARD_URL=https://$domain"
      echo "API_URL=https://$domain"
    fi
    echo
    echo "# Optional. These can also be entered in the dashboard's setup checklist."
    echo "TWILIO_ACCOUNT_SID="
    echo "TWILIO_AUTH_TOKEN="
    echo "TWILIO_PHONE_NUMBER="
    echo "GOOGLE_API_KEY="
  } > .env
  chmod 600 .env
  echo "Created .env with new secrets."
elif [ -n "${1:-}" ]; then
  echo "Keeping the existing .env (the domain argument only applies on the first run)."
fi

profile=()
if grep -qE '^DOMAIN=.+' .env; then
  profile=(--profile https)
fi

echo "Building and starting… (the first build takes a few minutes)"
docker compose "${profile[@]}" up -d --build

echo -n "Waiting for the server"
for _ in $(seq 1 90); do
  if docker compose exec -T backend python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" >/dev/null 2>&1; then
    break
  fi
  echo -n "."
  sleep 2
done
echo

dashboard="$(grep -E '^DASHBOARD_URL=' .env | cut -d= -f2- || true)"
dashboard="${dashboard:-http://localhost:3000}"
setup_link="$(docker compose logs backend 2>/dev/null | grep -o 'Finish setup at: [^ ]*' | tail -1 | cut -d' ' -f4 || true)"

echo
echo "The AI Calling Agent is running: $dashboard"
if [ -n "$setup_link" ]; then
  echo "Create your admin account here (one-time link):"
  echo "  $setup_link"
fi
echo "Logs: docker compose logs -f backend   ·   Stop: docker compose down"
